spring:
  application:
    name: account
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enable: false
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/astfx_account_db?allowPublicKeyRetrieval=true&sslMode=DISABLED}
    username: ${DB_USER:root}
    password: ${DB_PWD:1305}

server:
  port: 8762

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID:astroflix-microservices}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:WMKuDDHmR7OtDYO3rZBo0IjU2TCRvZLf}
  domain: ${KEYCLOAK_DOMAIN:localhost:8080}
  realm: ${REALM:astroflix-realm}
  username: ${KEYCLOAK_ADMIN_USERNAME:astroflix_admin}
  password: ${KEYCLOAK_ADMIN_PASSWORD:astroflix@admin}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000}